### ISSUE TITLE
Transfer ownership ?

### ISSUE THREAD

**Issue by pakal** [pakal/cmsplugin-rst#2]
Hello,

I've forked this plugin and improved misc stuffs on it (https://github.com/pakal/cmsplugin-rst), since you menion in another issue that you don't use it anymore and are willing to transfer ownership, could you please transfer it to me (pakal) on Pypi ?

thanks,
P.C

**Comment by ojii** [comment]
Hi Pakal,

Sure thing. However I can't transfer it to you on Github if you have a fork/repo with the same name.

**Comment by ojii** [comment]
Anyway, I've added you as an owner to the pypi package. Feel free to remove me from there. Let me know once you're ready for the github project to be transferred.

**Comment by pakal** [comment]
Thanks, I've removed you from pypi and renamed my fork, github transfer should work now.

**Comment by ojii** [comment]
Still can't do it:

> pakal already has a repository in the ojii/cmsplugin-rst network

**Comment by pakal** [comment]
OK hadn't understood that any fork was prohibited, I deleted mine, _now_ it should _really_ work.

**Comment by ojii** [comment]
done

**Comment by pakal** [comment]
Awesome, thanks
